/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecyclerRouteImport } from './routes/recycler'
import { Route as ManufacturerRouteImport } from './routes/manufacturer'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyItemIdRouteImport } from './routes/journey.$itemId'

const RecyclerRoute = RecyclerRouteImport.update({
  id: '/recycler',
  path: '/recycler',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturerRoute = ManufacturerRouteImport.update({
  id: '/manufacturer',
  path: '/manufacturer',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyItemIdRoute = JourneyItemIdRouteImport.update({
  id: '/journey/$itemId',
  path: '/journey/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/consumer': typeof ConsumerRoute
  '/manufacturer': typeof ManufacturerRoute
  '/recycler': typeof RecyclerRoute
  '/journey/$itemId': typeof JourneyItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/consumer': typeof ConsumerRoute
  '/manufacturer': typeof ManufacturerRoute
  '/recycler': typeof RecyclerRoute
  '/journey/$itemId': typeof JourneyItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collector': typeof CollectorRoute
  '/consumer': typeof ConsumerRoute
  '/manufacturer': typeof ManufacturerRoute
  '/recycler': typeof RecyclerRoute
  '/journey/$itemId': typeof JourneyItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collector'
    | '/consumer'
    | '/manufacturer'
    | '/recycler'
    | '/journey/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collector'
    | '/consumer'
    | '/manufacturer'
    | '/recycler'
    | '/journey/$itemId'
  id:
    | '__root__'
    | '/'
    | '/collector'
    | '/consumer'
    | '/manufacturer'
    | '/recycler'
    | '/journey/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectorRoute: typeof CollectorRoute
  ConsumerRoute: typeof ConsumerRoute
  ManufacturerRoute: typeof ManufacturerRoute
  RecyclerRoute: typeof RecyclerRoute
  JourneyItemIdRoute: typeof JourneyItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recycler': {
      id: '/recycler'
      path: '/recycler'
      fullPath: '/recycler'
      preLoaderRoute: typeof RecyclerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturer': {
      id: '/manufacturer'
      path: '/manufacturer'
      fullPath: '/manufacturer'
      preLoaderRoute: typeof ManufacturerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$itemId': {
      id: '/journey/$itemId'
      path: '/journey/$itemId'
      fullPath: '/journey/$itemId'
      preLoaderRoute: typeof JourneyItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectorRoute: CollectorRoute,
  ConsumerRoute: ConsumerRoute,
  ManufacturerRoute: ManufacturerRoute,
  RecyclerRoute: RecyclerRoute,
  JourneyItemIdRoute: JourneyItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
